"use client";

import Link from "next/link";
import {
  Activity, ArrowRight, BadgeCheck, Building2, CalendarDays, Check,
  ClipboardCheck, ClipboardList, FileText, Flag, ShieldCheck, UserRound,
  Users, XCircle,
} from "lucide-react";
import { useWorkflow } from "@/components/providers/WorkflowProvider";
import { DEMO_AGENT_AUTHORIZATIONS, DEMO_VERIFICATION_CASES, type VerificationCase } from "@/lib/portal-data";
import { recordVerificationDecision, type ListingStatus, type VerificationDecision, type VerificationHistoryEvent, type WorkspaceListing } from "@/lib/workflow";
import { BUTTON_PRIMARY, BUTTON_SECONDARY, DemoNotice, EmptyPanel, MetricCard, StatusBadge, WorkspaceHeading, WorkspacePanel } from "@/components/workspace/Primitives";
import { PreferencesPage } from "@/components/workspace/ProfileSettings";

export function AdminWorkspace({ section }: { section: string }) {
  if (section === "dashboard") return <AdminDashboard />;
  if (section === "verifications") return <AdminVerifications />;
  if (section === "parametres") return <PreferencesPage />;
  if (section === "statistiques") return <AdminStatistics />;
  return <AdminRecords section={section} />;
}

function AdminDashboard() {
  const { data } = useWorkflow();
  const decisions = data.verificationDecisions;
  const demoOpenCases = DEMO_VERIFICATION_CASES.filter((entry) => ["a-examiner", "modification-demandee"].includes(decisions[entry.id] ?? entry.initialDecision)).length;
  const submittedOpenCases = data.listings.filter((entry) => ["en-verification", "modification-demandee"].includes(data.listingStatusOverrides[entry.id] ?? entry.status)).length;
  const openCases = demoOpenCases + submittedOpenCases;
  const reports = 4;
  return <>
    <WorkspaceHeading eyebrow="HOMERA · supervision" title="Dashboard administratif" description="Vue de pilotage du système. Les compteurs préchargés sont fictifs et signalés comme tels dans cet environnement de démonstration." actions={<Link href="/admin/verifications" className={BUTTON_PRIMARY}><ClipboardCheck className="h-4 w-4" aria-hidden="true" />Traiter les vérifications</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={Users} label="Utilisateurs" value="1 284" detail="Donnée de démonstration" /><MetricCard icon={Building2} label="Propriétaires" value="326" detail="Comptes déclarés" /><MetricCard icon={ShieldCheck} label="Agents" value="82" detail="Profils identifiés" /><MetricCard icon={ClipboardCheck} label="Vérifications à traiter" value={openCases} detail="Sur la file pilote" /></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.05fr_0.95fr]"><WorkspacePanel title="File de vérification" description="Les contrôles de propriété et de mandat sont prioritaires." icon={ClipboardCheck} action={<Link href="/admin/verifications" className="text-caption font-semibold text-homera-terracotta hover:underline">Ouvrir la file</Link>}><ul className="divide-y divide-border">{DEMO_VERIFICATION_CASES.map((entry) => { const status = decisions[entry.id] ?? entry.initialDecision; return <li key={entry.id} className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0 last:pb-0"><div><p className="text-note font-semibold">{entry.title}</p><p className="mt-1 font-mono text-caption text-muted">{entry.reference} · {entry.city}</p></div><StatusBadge status={status} /></li>; })}</ul></WorkspacePanel><WorkspacePanel title="Activité plateforme" description="Tendances illustratives du système pilote." icon={Activity}><div className="space-y-4">{[{ label: "Biens publiés", value: "78 %", width: "78%" }, { label: "Visites confirmées", value: "64 %", width: "64%" }, { label: "Dossiers complets", value: "86 %", width: "86%" }].map((entry) => <div key={entry.label}><div className="flex justify-between text-caption"><span className="font-medium">{entry.label}</span><span className="homera-num text-muted">{entry.value}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-surface-hover"><div className="h-full rounded-full bg-homera-terracotta" style={{ width: entry.width }} /></div></div>)}</div><p className="mt-5 text-caption text-muted">Ces ratios ne proviennent pas d’un service analytique réel.</p></WorkspacePanel></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><QuickAdminLink href="/admin/utilisateurs" icon={Users} title="Utilisateurs" detail="Rôles et comptes" /><QuickAdminLink href="/admin/biens" icon={Building2} title="Biens" detail="Statuts de publication" /><QuickAdminLink href="/admin/visites" icon={CalendarDays} title="Visites" detail="Demandes et rendez-vous" /><QuickAdminLink href="/admin/signalements" icon={Flag} title="Signalements" detail={`${reports} dossiers de démonstration`} /></div>
  </>;
}

function AdminVerifications() {
  const { data, updateData } = useWorkflow();
  const decision = (id: string, value: VerificationDecision, title: string) => updateData((current) => recordVerificationDecision(current, id, value, title));
  const cases = DEMO_VERIFICATION_CASES;
  const submittedListings = data.listings;
  const statusForListing = (listing: WorkspaceListing) => data.verificationDecisions[listing.id] ?? decisionForListingStatus(data.listingStatusOverrides[listing.id] ?? listing.status);
  const isOpen = (status: VerificationDecision) => status === "a-examiner" || status === "modification-demandee";
  const isRejected = (status: VerificationDecision) => status === "refuse" || status === "suspendu";
  const waitingCount = cases.filter((item) => isOpen(data.verificationDecisions[item.id] ?? item.initialDecision)).length + submittedListings.filter((item) => isOpen(statusForListing(item))).length;
  const validatedCount = cases.filter((item) => (data.verificationDecisions[item.id] ?? item.initialDecision) === "valide").length + submittedListings.filter((item) => statusForListing(item) === "valide").length;
  const rejectedCount = cases.filter((item) => isRejected(data.verificationDecisions[item.id] ?? item.initialDecision)).length + submittedListings.filter((item) => isRejected(statusForListing(item))).length;
  return <>
    <WorkspaceHeading eyebrow="Contrôle documentaire" title="Vérifications des biens" description="Examinez les éléments déclarés avant publication. Une décision HOMERA décrit un contrôle documentaire, elle ne remplace ni un titre ni l’avis des autorités compétentes." actions={<span className="inline-flex min-h-10 items-center gap-2 rounded-full border border-warning/30 bg-warning/[0.07] px-3.5 text-caption font-semibold text-warning">{waitingCount} dossier(s) à examiner</span>} />
    <div className="mb-5 grid gap-3 md:grid-cols-3"><MetricCard icon={ClipboardCheck} label="Dossiers ouverts" value={waitingCount} detail="Démonstrations + soumissions locales" /><MetricCard icon={BadgeCheck} label="Validés" value={validatedCount} detail="Dans ce navigateur" /><MetricCard icon={XCircle} label="Refusés / suspendus" value={rejectedCount} detail="Décisions locales" /></div>
    {!cases.length && !submittedListings.length ? <EmptyPanel icon={ClipboardCheck} title="Aucun dossier à vérifier" description="Les nouveaux dossiers propriétaires apparaîtront ici après leur soumission." /> : <div className="space-y-5">{cases.map((entry) => <VerificationCaseCard key={entry.id} item={entry} status={data.verificationDecisions[entry.id] ?? entry.initialDecision} onDecision={(value, label) => decision(entry.id, value, label)} />)}{submittedListings.map((listing) => <SubmittedListingReviewCard key={listing.id} item={listing} status={statusForListing(listing)} history={data.verificationHistory[listing.id] ?? []} onDecision={(value, label) => decision(listing.id, value, label)} />)}</div>}
    <div className="mt-6"><DemoNotice>Les dossiers de démonstration et les nouvelles soumissions locales ne déclenchent pas de vérification foncière réelle. Une décision de prototype ne publie pas l’annonce à l’extérieur de ce navigateur.</DemoNotice></div>
  </>;
}

function SubmittedListingReviewCard({ item, status, history, onDecision }: { item: WorkspaceListing; status: VerificationDecision; history: VerificationHistoryEvent[]; onDecision: (value: VerificationDecision, label: string) => void }) {
  const activeAuthorization = DEMO_AGENT_AUTHORIZATIONS.find((entry) => entry.agentId === item.agentId && entry.propertyRef === item.reference && entry.status === "active");
  const events = history.length ? [...history].reverse() : [{ id: `submission-${item.id}`, createdAt: item.submittedAt, title: "Dossier soumis", detail: "Le dossier est entré dans la file de contrôle.", decision: "a-examiner" as const }];
  const priceUnit = item.intent === "louer" ? " / mois" : item.intent === "sejour" ? " / nuitée" : "";
  return <WorkspacePanel title={item.title} description={`${item.reference} · ${item.district}, ${item.city} · soumis le ${formatDate(item.submittedAt)}`} icon={Building2} action={<StatusBadge status={status} />}>
    <div className="grid gap-5 xl:grid-cols-[1.05fr_0.95fr]">
      <div className="space-y-4">
        <section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Propriétaire & bien</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><AdminInfoCell label="Propriétaire déclaré" value={item.ownerName || "Titulaire du compte connecté"} /><AdminInfoCell label="Contact pilote" value={item.ownerEmail || "Non renseigné"} /><AdminInfoCell label="Localisation" value={`${item.district}, ${item.city}`} /><AdminInfoCell label="Projet & type" value={`${listingIntentLabel(item.intent)} · ${item.type}`} /><AdminInfoCell label="Prix déclaré" value={`${new Intl.NumberFormat("fr-FR").format(item.price)} FCFA${priceUnit}`} /><AdminInfoCell label="Surface" value={item.draftSnapshot?.surface ? `${item.draftSnapshot.surface} m²` : "Non renseignée"} /></dl></section>
        <section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Pièces déclarées</h3>{item.documentNames.length ? <ul className="mt-3 space-y-2">{item.documentNames.map((name) => <li key={name} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-border px-3 py-2 text-note"><span>{name}</span><span className="rounded-full bg-warning/10 px-2.5 py-1 text-[0.66rem] font-semibold text-warning">À vérifier</span></li>)}</ul> : <p className="mt-3 text-note text-error">Aucune pièce déclarée.</p>}<p className="mt-3 text-caption leading-relaxed text-muted">Les noms de fichiers seulement sont conservés dans le prototype; aucun document n’a été téléversé.</p></section>
        <section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Agent / représentant</h3>{item.agentId ? <><p className="mt-3 text-note font-semibold">Matricule {item.agentId}</p><p className="mt-1 text-caption leading-relaxed text-muted">Mandat déclaré par le propriétaire : {item.mandateDeclared ? "oui" : "non"}.</p>{activeAuthorization ? <Link href={`/verification-agent?agent=${encodeURIComponent(item.agentId!)}&bien=${encodeURIComponent(item.reference)}`} className="mt-2 inline-flex min-h-9 items-center gap-1.5 text-caption font-semibold text-homera-terracotta hover:underline">Vérifier l’autorisation exacte<ArrowRight className="h-3.5 w-3.5" aria-hidden="true" /></Link> : <p className="mt-2 text-caption font-semibold text-warning">Aucune autorisation active n’est enregistrée pour cette référence précise.</p>}</> : <p className="mt-3 text-note text-muted">Aucun agent n’a été déclaré sur ce dossier.</p>}</section>
      </div>
      <div className="space-y-4"><section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Déclarations à contrôler</h3><ul className="mt-3 space-y-3"><li className="flex gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-warning" aria-hidden="true" /><span className="text-note">Propriétaire / mandataire déclaré : <strong>{item.ownerDeclared ? "oui" : "non"}</strong></span></li><li className="flex gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-warning" aria-hidden="true" /><span className="text-note">Mandat couvrant ce bien : <strong>{item.agentId && item.mandateDeclared ? "déclaré, à contrôler" : "non établi"}</strong></span></li><li className="flex gap-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-warning" aria-hidden="true" /><span className="text-note">Photos annoncées : <strong>{item.photoNames.length}</strong> · Pièces listées : <strong>{item.documentNames.length}</strong></span></li></ul></section>
        <section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Historique du dossier</h3><ol className="mt-3 space-y-3">{events.map((event) => <li key={event.id} className="relative border-l border-border pl-4"><span className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-homera-terracotta" aria-hidden="true" /><p className="text-note font-semibold">{event.title}</p><p className="mt-0.5 text-[0.67rem] text-muted">{formatDate(event.createdAt)}</p><p className="mt-1 text-caption leading-relaxed text-muted">{event.detail}</p></li>)}</ol></section>
      </div>
    </div>
    <div className="mt-5 flex flex-wrap gap-2 border-t border-border pt-4"><button type="button" onClick={() => onDecision("valide", "Bien validé (démo)")} className={BUTTON_PRIMARY}><Check className="h-4 w-4" aria-hidden="true" />Valider</button><button type="button" onClick={() => onDecision("modification-demandee", "Modification demandée")} className={BUTTON_SECONDARY}>Demander une modification</button><button type="button" onClick={() => onDecision("refuse", "Dossier refusé")} className={`${BUTTON_SECONDARY} hover:border-error/50 hover:text-error`}><XCircle className="h-4 w-4" aria-hidden="true" />Refuser</button><button type="button" onClick={() => onDecision("suspendu", "Bien suspendu")} className={`${BUTTON_SECONDARY} hover:border-error/50 hover:text-error`}>Suspendre</button>{status !== "a-examiner" && <button type="button" onClick={() => onDecision("a-examiner", "Dossier rouvert")} className="min-h-11 rounded-btn px-3 text-caption font-semibold text-muted hover:text-foreground">Rouvrir le contrôle</button>}</div>
  </WorkspacePanel>;
}

function decisionForListingStatus(status: ListingStatus): VerificationDecision {
  if (status === "modification-demandee") return "modification-demandee";
  if (status === "suspendu") return "suspendu";
  if (["verifie", "publie", "indisponible", "loue"].includes(status)) return "valide";
  return "a-examiner";
}

function listingIntentLabel(intent: WorkspaceListing["intent"]): string {
  if (intent === "louer") return "Location";
  if (intent === "sejour") return "Séjour";
  return "Vente";
}

function VerificationCaseCard({ item, status, onDecision }: { item: VerificationCase; status: VerificationDecision; onDecision: (value: VerificationDecision, label: string) => void }) {
  return <WorkspacePanel title={item.title} description={`${item.reference} · ${item.city} · soumis le ${formatDate(item.submittedAt)}`} icon={ShieldCheck} action={<StatusBadge status={status} />}>
    <div className="grid gap-5 xl:grid-cols-[1.05fr_0.95fr]">
      <div className="space-y-4"><section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Propriétaire & bien</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2">{[["Propriétaire", item.owner], ["Contact pilote", item.ownerEmail], ...item.information.map((info) => [info.label, info.value])].map(([label, value]) => <div key={label}><dt className="text-[0.66rem] text-muted">{label}</dt><dd className="mt-0.5 text-note font-semibold">{value}</dd></div>)}</dl></section>
        <section><h3 className="mb-2 flex items-center gap-2 text-caption font-semibold uppercase tracking-[0.14em] text-muted"><FileText className="h-3.5 w-3.5" aria-hidden="true" />Documents transmis</h3><ul className="space-y-2">{item.documents.map((document) => <li key={document.name} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-border bg-background px-3 py-2.5"><span className="text-note">{document.name}</span><span className={`rounded-full px-2.5 py-1 text-[0.66rem] font-semibold ${document.state === "reçu" ? "bg-success/10 text-success" : document.state === "manquant" ? "bg-error/10 text-error" : "bg-warning/10 text-warning"}`}>{document.state}</span></li>)}</ul></section>
        <section className="rounded-2xl border border-border bg-background p-4"><h3 className="flex items-center gap-2 text-caption font-semibold uppercase tracking-[0.14em] text-muted"><UserRound className="h-3.5 w-3.5" aria-hidden="true" />Agent / représentant</h3><p className="mt-3 text-note font-semibold">{item.agentName} · {item.agentId}</p><p className="mt-1 text-caption leading-relaxed text-muted">{item.agentProof}</p><Link href={`/verification-agent?agent=${item.agentId}&bien=${item.reference}`} className="mt-2 inline-flex min-h-9 items-center gap-1.5 text-caption font-semibold text-homera-terracotta hover:underline">Vérifier l’autorisation<ArrowRight className="h-3.5 w-3.5" aria-hidden="true" /></Link></section>
      </div>
      <div className="space-y-4"><section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Éléments à contrôler</h3><ul className="mt-3 space-y-3">{item.checks.map((check) => <li key={check.label} className="flex gap-3"><span className="mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-border text-muted"><span className="sr-only">À contrôler</span><span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-warning" /></span><span><span className="block text-note font-semibold">{check.label}</span><span className="mt-0.5 block text-caption leading-relaxed text-muted">{check.detail}</span></span></li>)}</ul></section>
        <section className="rounded-2xl border border-border bg-background p-4"><h3 className="text-caption font-semibold uppercase tracking-[0.14em] text-muted">Historique du dossier</h3><ol className="mt-3 space-y-3">{item.history.map((event) => <li key={`${event.date}-${event.title}`} className="relative border-l border-border pl-4"><span className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-homera-terracotta" aria-hidden="true" /><p className="text-note font-semibold">{event.title}</p><p className="mt-0.5 text-[0.67rem] text-muted">{formatDate(event.date)}</p><p className="mt-1 text-caption leading-relaxed text-muted">{event.detail}</p></li>)}</ol></section>
      </div>
    </div>
    <div className="mt-5 flex flex-wrap gap-2 border-t border-border pt-4"><button type="button" onClick={() => onDecision("valide", "Bien validé (démo)")} className={BUTTON_PRIMARY}><Check className="h-4 w-4" aria-hidden="true" />Valider</button><button type="button" onClick={() => onDecision("modification-demandee", "Modification demandée")} className={BUTTON_SECONDARY}>Demander une modification</button><button type="button" onClick={() => onDecision("refuse", "Dossier refusé")} className={`${BUTTON_SECONDARY} hover:border-error/50 hover:text-error`}><XCircle className="h-4 w-4" aria-hidden="true" />Refuser</button><button type="button" onClick={() => onDecision("suspendu", "Bien suspendu")} className={`${BUTTON_SECONDARY} hover:border-error/50 hover:text-error`}>Suspendre</button>{status !== "a-examiner" && <button type="button" onClick={() => onDecision("a-examiner", "Dossier rouvert")} className="min-h-11 rounded-btn px-3 text-caption font-semibold text-muted hover:text-foreground">Rouvrir le contrôle</button>}</div>
  </WorkspacePanel>;
}

function AdminStatistics() {
  const rows = [{ label: "Vérifications reçues", value: "146", amount: 78 }, { label: "Visites demandées", value: "92", amount: 58 }, { label: "Dossiers de location", value: "37", amount: 42 }, { label: "Autorisations agent", value: "214", amount: 83 }];
  return <><WorkspaceHeading eyebrow="Pilotage de l’activité" title="Statistiques" description="Indicateurs maquettes, conçus pour valider la hiérarchie et le contenu du futur tableau de bord." /><WorkspacePanel title="Activité du mois" description="Volumes fictifs · aucun calcul analytique serveur." icon={Activity}><div className="space-y-5">{rows.map((row) => <div key={row.label}><div className="flex items-center justify-between gap-3"><p className="text-note font-semibold">{row.label}</p><p className="homera-num font-serif text-display-xs">{row.value}</p></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-surface-hover"><div className="h-full rounded-full bg-homera-terracotta" style={{ width: `${row.amount}%` }} /></div></div>)}</div></WorkspacePanel></>;
}

function AdminRecords({ section }: { section: string }) {
  const content: Record<string, { title: string; eyebrow: string; description: string; icon: typeof Users; rows: { name: string; detail: string; status: string }[] }> = {
    utilisateurs: { title: "Utilisateurs", eyebrow: "Comptes & accès", description: "Vérifiez les informations de compte et les rôles déclarés.", icon: Users, rows: [{ name: "Clarisse Ahouansou", detail: "Propriétaire · Cotonou", status: "Compte vérifié (démo)" }, { name: "Koffi Ahouansou", detail: "Agent · AG-HOM-0248", status: "Actif (démo)" }, { name: "Client pilote", detail: "Client · Abomey-Calavi", status: "Adresse à confirmer" }] },
    proprietaires: { title: "Propriétaires", eyebrow: "Profils propriétaire", description: "Portefeuilles, coordonnées et pièces déclarées.", icon: UserRound, rows: [{ name: "Clarisse Ahouansou", detail: "2 biens · Cotonou", status: "Profil en revue" }, { name: "Éric Hounkpatin", detail: "1 bien · Haie Vive", status: "Document manquant" }] },
    agents: { title: "Agents", eyebrow: "Identité & mandats", description: "Les habilitations s’évaluent bien par bien, jamais comme un accès général aux annonces.", icon: ShieldCheck, rows: [{ name: "Koffi Ahouansou", detail: "AG-HOM-0248 · 3 mandats actifs", status: "Actif (démo)" }, { name: "Aïcha Sètondji", detail: "AG-HOM-0312 · Akpakpa", status: "Mandat à vérifier" }] },
    biens: { title: "Biens", eyebrow: "Catalogue administratif", description: "Statut de publication, de vérification et de disponibilité.", icon: Building2, rows: DEMO_VERIFICATION_CASES.map((item) => ({ name: item.title, detail: `${item.reference} · ${item.city}`, status: item.initialDecision === "a-examiner" ? "En vérification" : "Publié" })) },
    visites: { title: "Visites", eyebrow: "Rendez-vous", description: "Suivi des demandes et des créneaux du pilote.", icon: CalendarDays, rows: [{ name: "Aucune donnée serveur", detail: "Les visites sont stockées par compte dans le navigateur.", status: "Mode pilote" }] },
    demandes: { title: "Demandes", eyebrow: "Parcours locatif", description: "Candidatures, décisions, contrats et remise des clés.", icon: ClipboardList, rows: [{ name: "Aucun dossier serveur", detail: "Les demandes sont locales au compte.", status: "Mode pilote" }] },
    signalements: { title: "Signalements", eyebrow: "Confiance & sécurité", description: "File de démonstration pour les signalements de fiche, mandat ou contenu.", icon: Flag, rows: [{ name: "Prix à confirmer", detail: "HOM-CTN-000422 · signalement pilote", status: "À étudier" }, { name: "Photo à revoir", detail: "HOM-CAL-000108 · signalement pilote", status: "En attente" }, { name: "Mandat expirant", detail: "AG-HOM-0312 · rappel pilote", status: "À vérifier" }] },
    documents: { title: "Documents", eyebrow: "Dossiers documentaires", description: "Pièces jointes déclarées et dates de contrôle.", icon: FileText, rows: DEMO_VERIFICATION_CASES.flatMap((item) => item.documents.map((doc) => ({ name: doc.name, detail: item.reference, status: doc.state }))) },
  };
  const item = content[section] ?? content.utilisateurs;
  const Icon = item.icon;
  return <><WorkspaceHeading eyebrow={item.eyebrow} title={item.title} description={item.description} /><WorkspacePanel title={item.title} description="Données de démonstration · aucun enregistrement réel" icon={Icon}>
    <ul className="space-y-3 sm:hidden" aria-label={item.title}>{item.rows.map((row, index) => <li key={`${row.name}-${index}`} className="rounded-xl border border-border bg-background p-3"><p className="text-note font-semibold">{row.name}</p><p className="mt-1 text-caption leading-relaxed text-muted">{row.detail}</p><span className="mt-2 inline-flex rounded-full border border-border bg-card px-2.5 py-1 text-[0.68rem] font-semibold">{row.status}</span></li>)}</ul>
    <div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[560px] border-collapse text-left text-note"><thead><tr className="border-b border-border text-caption text-muted"><th scope="col" className="pb-3 pr-4 font-semibold">Élément</th><th scope="col" className="pb-3 pr-4 font-semibold">Détail</th><th scope="col" className="pb-3 font-semibold">État</th></tr></thead><tbody>{item.rows.map((row, index) => <tr key={`${row.name}-${index}`} className="border-b border-border/70 last:border-0"><td className="py-4 pr-4 font-semibold">{row.name}</td><td className="py-4 pr-4 text-caption text-muted">{row.detail}</td><td className="py-4"><span className="inline-flex rounded-full border border-border bg-background px-2.5 py-1 text-[0.68rem] font-semibold">{row.status}</span></td></tr>)}</tbody></table></div>
  </WorkspacePanel><div className="mt-6"><DemoNotice>Les données administratives ne sont pas connectées. Cette interface sert à valider les pages, états et actions avant la mise en place d’une API et d’un contrôle d’accès sécurisé.</DemoNotice></div></>;
}

function AdminInfoCell({ label, value }: { label: string; value: string }) {
  return <div><dt className="text-[0.66rem] text-muted">{label}</dt><dd className="mt-0.5 break-words text-note font-semibold">{value}</dd></div>;
}

function QuickAdminLink({ href, icon: Icon, title, detail }: { href: string; icon: typeof Users; title: string; detail: string }) {
  return <Link href={href} className="group rounded-card border border-border bg-card p-4 shadow-[var(--shadow-card)] transition-colors hover:border-homera-terracotta/35"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-homera-terracotta/[0.08] text-homera-terracotta"><Icon className="h-4 w-4" aria-hidden="true" /></span><span className="mt-3 block text-note font-semibold">{title}</span><span className="mt-1 block text-caption text-muted">{detail}</span></Link>;
}
function formatDate(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("fr-FR", { day: "numeric", month: "short", year: "numeric" }).format(date); }
