// GÉNÉRÉ AUTOMATIQUEMENT par scripts/build-images.mjs — ne pas éditer à la main.
// Régénérer avec : npm run images

export type MediaAsset = {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  readonly blurDataURL: string;
};

export const MEDIA: Record<string, MediaAsset> = {
  "intent-acheter": {
    "src": "/images/intent-acheter.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBv/EACEQAAIBBAICAwAAAAAAAAAAAAECAwAEERIhQRNxMTKh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwL/xAAXEQEBAQEAAAAAAAAAAAAAAAABAEER/9oADAMBAAIRAxEAPwC9bq1ntpZXjKhM6hh9uM8VnnM94/l0CR8gBmAH780tL+YxRxy4cRjCk9UqSOa42dCzZPB2yQPXVBxnEmWahrIFgCQGwT7FRSkhCQSDv16ooqzY8L//2Q=="
  },
  "intent-louer": {
    "src": "/images/intent-louer.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAAF/8QAIxAAAQQCAQMFAAAAAAAAAAAAAQACAwQREnETMUEhIjRhof/EABYBAQEBAAAAAAAAAAAAAAAAAAMAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAAgP/2gAMAwEAAhEDEQA/AHU6800bfdESWhxBCFd61KMOm6Ugc8gOA59PxHpXo7DJHF0plDtY9X4OPA4+0e1eNisK9jaJ0chPbJOc+EKEwtjUCRchIJB3b25Wrd+Q/lSlbtcr/9k="
  },
  "intent-sejourner": {
    "src": "/images/intent-sejourner.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAQFA//EACAQAQABBAICAwAAAAAAAAAAAAECAAMRIQQSInExQWH/xAAWAQEBAQAAAAAAAAAAAAAAAAACAQP/xAAaEQADAAMBAAAAAAAAAAAAAAAAAQIDESFB/9oADAMBAAIRAxEAPwCEWbcTrCcZyTsIfHulpxuRkwjMZDlw07Zh3WcbsZoB461jGPdbPG5M0bFrYYkxjRWW9aHUwn1i/HccckaR0n1VTi3rrYVuTXJvs/tFFZombw//2Q=="
  },
  "intent-investir": {
    "src": "/images/intent-investir.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQCAwX/xAAjEAABBAEDBAMAAAAAAAAAAAABAAIDESEEEiIFEzFBUWFy/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQP/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIDMf/aAAwDAQACEQMRAD8Ag7X6yuMrz92VU/qWpaec0p/L6Sz5SYd9kD2AlHy0cux5BChLZWpSGgB2qrG1Z0mHur5QhMDpxH//2Q=="
  },
  "prop-villa": {
    "src": "/images/prop-villa.jpg",
    "width": 1440,
    "height": 900,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAJAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIxABAAECAwkAAAAAAAAAAAAAAQIABAMRIQUGEhQxMkFx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8ARDeK5lbHL2Ikc9HQDxWXj7UulZY7iEl04JI5fKFZ9j6qsulTVePBZZ//2Q=="
  },
  "prop-appartement": {
    "src": "/images/prop-appartement.jpg",
    "width": 1440,
    "height": 900,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAJAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIF/8QAIBAAAQMEAgMAAAAAAAAAAAAAAQACAwURIYEiMQRE8P/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGBEBAAMBAAAAAAAAAAAAAAAAEQABAhL/2gAMAwEAAhEDEQA/ABNVbIQ7DA4cur/aVxVGCDjI4SA5y65G1je1JtP4XRU1vSsecgT/2Q=="
  },
  "prop-terrain": {
    "src": "/images/prop-terrain.jpg",
    "width": 1440,
    "height": 900,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAJAA4DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAD/xAAfEAEAAQQCAwEAAAAAAAAAAAABAgADBBESMTNBUXH/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAGREAAgMBAAAAAAAAAAAAAAAAAAIBAxNR/9oADAMBAAIRAxEAPwBTmXuSyvO/SwNa+Ua9n5UZPDItovSBqp8cfwo93uixY3ReKn//2Q=="
  },
  "prop-duplex": {
    "src": "/images/prop-duplex.jpg",
    "width": 1440,
    "height": 900,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAJAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAED/8QAJBAAAgECAwkAAAAAAAAAAAAAAQIDAAQFESESEyIzNHGhwfH/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECQf/aAAwDAQACEQMRAD8AHaFGl32yoXPQMQD8raZy6W7W0ixcBzLLkDr5NEh5pqYn0cPf1RVWCnOn/9k="
  },
  "service-gestion": {
    "src": "/images/service-gestion.jpg",
    "width": 1280,
    "height": 960,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAKAA4DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABQb/xAAjEAACAQMDBAMAAAAAAAAAAAABAgMAESEEBRITIjFBJFGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABcRAQEBAQAAAAAAAAAAAAAAAAEAMUH/2gAMAwEAAhEDEQA/AEm3V9VKnQVjCTawFyPzwKA3gJ8dZFdSsYUqwtkewaY5GPQrwJXsPjH1U5oiZZZWlJdrnLZPqiclDl//2Q=="
  },
  "service-maintenance": {
    "src": "/images/service-maintenance.jpg",
    "width": 1280,
    "height": 960,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAKAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIBAAAwABBAIDAAAAAAAAAAAAAQIDAAUhIkEEEhFxgf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAVEQEBAAAAAAAAAAAAAAAAAAAAYf/aAAwDAQACEQMRAD8ALq2oUpPx5o5mtByZifwfWNOqJL1lSyqVUcRv8bDvvLanCLUh7SmePajM60ZNdi0kOwG6jChK/9k="
  },
  "service-demenagement": {
    "src": "/images/service-demenagement.jpg",
    "width": 1280,
    "height": 960,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAKAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIBAAAgEDBAMAAAAAAAAAAAAAAQIDAAQhBhETMRIUsf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAXEQADAQAAAAAAAAAAAAAAAAAAARES/9oADAMBAAIRAxEAPwBHlk9nhiLhSmSozuMUEV+sNxK92OMBiigjqqtgNrskYPg32s7qUbXLEd8jZos1CU//2Q=="
  },
  "service-travaux": {
    "src": "/images/service-travaux.jpg",
    "width": 1280,
    "height": 960,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAKAA4DASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIDBP/EAB4QAAICAgMBAQAAAAAAAAAAAAECAxEEIQASMRNB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAWEQADAAAAAAAAAAAAAAAAAAAAEVH/2gAMAwEAAhEDEQA/ALQTRZcmKj0OilCfzzXM2QsQlPUqwGjR8PCZHGYsYdhH9iOt6qzquPlIgc0qi2s695OqO4f/2Q=="
  },
  "editorial-architecture": {
    "src": "/images/editorial-architecture.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAUGA//EACQQAAEDBAEDBQAAAAAAAAAAAAEAAgMEERIxBQZBUSEiJGFx/8QAFgEBAQEAAAAAAAAAAAAAAAAAAwIE/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAIBAxEhMf/aAAwDAQACEQMRAD8Az6p4xsUT6mJtg62QHm+1Ltjeext+K25itgruEmwIyGN2nY9QpOQ4gBot9rOjaHaMDaIfJaOx2PKUVJIJsSPcdIQoUW3h/9k="
  },
  "editorial-quartier": {
    "src": "/images/editorial-quartier.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMEBf/EACAQAAICAQQDAQAAAAAAAAAAAAECAAMRBAUhMRITQUL/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABcRAQEBAQAAAAAAAAAAAAAAAAIAAQT/2gAMAwEAAhEDEQA/ADVbd6kZwucfJjPetdQNgBYnonHEvXdNQ2iWgMyEfvtsRBrC2eaXq1jKMgrnEO9KyZ5SqRCeOY0dmEJFVzf/2Q=="
  },
  "editorial-lifestyle": {
    "src": "/images/editorial-lifestyle.jpg",
    "width": 1100,
    "height": 1375,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAASAA4DASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQBAwX/xAAmEAACAQMCBAcAAAAAAAAAAAABAgMAESEFMQQGUWESEzNBcYGR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwL/xAAYEQADAQEAAAAAAAAAAAAAAAAAATESIf/aAAwDAQACEQMRAD8Atg0DTZ9OjaQFJSDdlkF9+m1Zp5ehkgDwSvIxYjy3IjKjOfelk1TiFVPFM6gKSLnub/dTLxihQxZVvkmQklu+KBaG4IwZiUHbp+UjN6rfNFFIqQ4f/9k="
  },
  "cta-night": {
    "src": "/images/cta-night.jpg",
    "width": 1915,
    "height": 821,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABMNDhEODBMRDxEVFBMXHTAfHRoaHToqLCMwRT1JR0Q9Q0FMVm1dTFFoUkFDX4JgaHF1e3x7SlyGkIV3j214e3b/2wBDARQVFR0ZHTgfHzh2T0NPdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnb/wAARCAAGAA4DASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAIG/8QAHRAAAQQCAwAAAAAAAAAAAAAAAQADERICEwQhgf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQEBAQAAAAAAAAAAAAAAAAABAFH/2gAMAwEAAhEDEQA/AMxtbtcM1g9C0wqd5DLsHXn6URGrsgF//9k="
  }
} as const;

export type MediaKey = keyof typeof MEDIA;
