import Link from "next/link";
import { ArrowRight, CheckCircle2, Home, Paintbrush, Truck, Wrench } from "lucide-react";
import { SERVICES } from "@/lib/content";
import { PageHero } from "@/components/catalog/PageHero";
import { Visual } from "@/components/ui/Visual";

const SERVICE_SLUGS: Record<string, string> = { gestion: "gestion-immobiliere", maintenance: "maintenance", demenagement: "demenagement", travaux: "travaux" };
const ICONS = { gestion: Home, maintenance: Wrench, demenagement: Truck, travaux: Paintbrush };

export function serviceHref(id: string): string { return `/services/${SERVICE_SLUGS[id] ?? id}`; }
export function serviceBySlug(slug: string) { return SERVICES.find((entry) => SERVICE_SLUGS[entry.id] === slug); }

export function ServiceDetail({ slug }: { slug: string }) {
  const service = serviceBySlug(slug);
  if (!service) return null;
  const Icon = ICONS[service.id as keyof typeof ICONS] ?? Home;
  return <>
    <PageHero crumbs={[{ label: "Accueil", href: "/" }, { label: "Services", href: "/services" }, { label: service.title }]} eyebrow={`Services HOMERA · ${service.index}`} title={service.title} intro={service.description} facts={[{ label: "Accompagnement", value: "De bout en bout" }, { label: "Équipe", value: "Intervenants identifiés" }, { label: "Suivi", value: "Documenté" }]} actions={<Link href={`/contact?service=${service.id}`} className="homera-press inline-flex min-h-11 items-center gap-2 rounded-btn homera-cta px-4 text-note font-semibold text-white">Parler à un conseiller<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link>} />
    <section className="mx-auto grid max-w-7xl gap-8 px-4 pb-20 pt-10 sm:px-6 lg:grid-cols-[1fr_0.85fr] lg:gap-12 lg:px-8"><div className="relative min-h-[280px] overflow-hidden rounded-card sm:min-h-[400px]"><Visual mediaKey={service.media} alt={service.alt} sizes="(min-width: 1024px) 48vw, 94vw" priority veil="soft" quality={72} className="absolute inset-0 h-full w-full"><div className="absolute inset-x-5 bottom-5 z-[2] text-white sm:inset-x-7 sm:bottom-7"><p className="text-caption font-semibold uppercase tracking-[0.17em] text-homera-amber">{service.short}</p><p className="mt-2 max-w-lg font-serif text-display-sm">Un service pensé pour durer.</p></div></Visual></div>
      <div className="flex flex-col justify-center"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-homera-terracotta/[0.09] text-homera-terracotta"><Icon className="h-5 w-5" aria-hidden="true" /></span><p className="mt-5 text-caption font-semibold uppercase tracking-[0.18em] text-homera-terracotta">Notre accompagnement</p><h2 className="mt-2 font-serif text-display-sm">Des étapes claires, du premier échange au suivi.</h2><ul className="mt-6 space-y-4">{service.bullets.map((bullet) => <li key={bullet} className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-success" aria-hidden="true" /><span className="text-body-sm leading-relaxed">{bullet}</span></li>)}</ul><p className="mt-6 text-note leading-relaxed text-muted">Chaque intervention fait l’objet d’un échange préalable : besoins, périmètre, calendrier et conditions sont clarifiés avant tout engagement.</p><Link href={`/contact?service=${service.id}`} className="mt-7 inline-flex min-h-12 w-fit items-center gap-2 rounded-btn homera-cta px-5 text-note font-semibold text-white">Décrire mon besoin<ArrowRight className="h-4 w-4" aria-hidden="true" /></Link><p className="mt-3 text-caption text-muted">Aucune réservation ou facturation n’est activée dans le pilote.</p></div></section>
    <section className="border-y border-border bg-card/50"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-12 sm:px-6 md:grid-cols-3 lg:px-8">{[{ title: "Un interlocuteur", text: "Un point de contact pour qualifier et suivre la demande." }, { title: "Un cadre annoncé", text: "Les conditions et le périmètre sont précisés avant intervention." }, { title: "Une trace utile", text: "Les documents et informations clés sont conservés dans le dossier." }].map((item) => <article key={item.title} className="rounded-card border border-border bg-background p-5"><p className="font-serif text-display-xs">{item.title}</p><p className="mt-2 text-note leading-relaxed text-muted">{item.text}</p></article>)}</div></section>
    <nav aria-label="Autres services HOMERA" className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-caption font-semibold uppercase tracking-[0.16em] text-muted">À découvrir également</p><ul className="mt-4 flex flex-wrap gap-2">{SERVICES.filter((entry) => entry.id !== service.id).map((entry) => <li key={entry.id}><Link href={serviceHref(entry.id)} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-border bg-card px-4 text-note font-medium hover:border-homera-terracotta hover:text-homera-terracotta">{entry.title}<ArrowRight className="h-3.5 w-3.5" aria-hidden="true" /></Link></li>)}</ul></nav>
  </>;
}
